import { NextResponse } from "next/server";
import { ollamaChat, OLLAMA_MODEL } from "@/lib/ollama";
import type {
  BeaconRequest,
  BeaconRequestItem,
  BeaconResponse,
} from "@/types";

/**
 * POST /api/beacon
 *
 * Accepts a list of flagged inventory items and returns one plain-English
 * reorder rationale per item, generated by a local Ollama model. The route
 * does no math — it receives numbers the client already computed and asks the
 * model to turn each set of numbers into a single founder-readable sentence.
 *
 * All model calls happen here, server-side, against a local Ollama instance —
 * nothing leaves the machine and there is no API key.
 */

const SYSTEM_PROMPT =
  "You are Beacon, an AI purchasing co-pilot for independent CPG brands. You write short, direct purchasing alerts for brand founders. You speak like a smart operator — not a software product, not an accountant. One sentence max. Be specific about the numbers. Never use words like 'it is recommended' or 'please consider'.";

const FALLBACK_RATIONALE = "Order now to avoid stockout.";

function buildUserPrompt(item: BeaconRequestItem): string {
  return `Item: ${item.name}. Days of stock remaining: ${item.daysRemaining}. Supplier lead time: ${item.leadTimeDays} days. We need to order ${item.reorderQty} ${item.unit} from ${item.supplier}. Write one sentence explaining why this needs to be ordered now.`;
}

async function generateRationale(item: BeaconRequestItem): Promise<string> {
  try {
    const text = await ollamaChat(
      [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: buildUserPrompt(item) },
      ],
      { numPredict: 120, temperature: 0.7 },
    );

    return text.length > 0 ? text : FALLBACK_RATIONALE;
  } catch (error) {
    // One item failing should never sink the whole bundle — degrade gracefully.
    console.error(`Beacon rationale failed for "${item.name}":`, error);
    return FALLBACK_RATIONALE;
  }
}

export async function POST(request: Request): Promise<NextResponse> {
  let body: BeaconRequest;
  try {
    body = (await request.json()) as BeaconRequest;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const items = body.items;
  if (!Array.isArray(items)) {
    return NextResponse.json(
      { error: "Expected an `items` array." },
      { status: 400 },
    );
  }

  // Generate every rationale in parallel — the calls are independent.
  const rationaleList = await Promise.all(
    items.map((item) => generateRationale(item)),
  );

  const rationales = items.reduce<Record<string, string>>(
    (acc, item, index) => {
      acc[item.name] = rationaleList[index];
      return acc;
    },
    {},
  );

  // Surface which local model produced the rationales (handy when demoing).
  const label = items.map((item) => item.name).join(", ");
  console.log(`[Beacon] ${OLLAMA_MODEL} → ${label || "(no items)"}`);

  const payload: BeaconResponse = { rationales };
  return NextResponse.json(payload);
}
