import type { InventoryItem } from "@/types";

/**
 * Static mock inventory for Han's Kombucha.
 *
 * This is a POC — there is no database. Velocities and lead times are tuned so
 * the demo surfaces a realistic mix of urgent, watch, and healthy SKUs across
 * four suppliers.
 */
export const HANS_KOMBUCHA_INVENTORY: InventoryItem[] = [
  {
    id: "sku-001",
    name: "Organic cane sugar",
    unit: "lbs",
    onHand: 48,
    dailyVelocity: 9.2,
    leadTimeDays: 14,
    supplier: "Wholesome Sweeteners",
    unitCost: 1.2,
    reorderQty: 200,
    category: "ingredient",
  },
  {
    id: "sku-002",
    name: "Ginger root extract",
    unit: "oz",
    onHand: 22,
    dailyVelocity: 5.8,
    leadTimeDays: 10,
    supplier: "Pacific Botanicals",
    unitCost: 3.4,
    reorderQty: 100,
    category: "ingredient",
  },
  {
    id: "sku-003",
    name: "SCOBY cultures",
    unit: "units",
    onHand: 6,
    dailyVelocity: 1.1,
    leadTimeDays: 7,
    supplier: "Pacific Botanicals",
    unitCost: 12.0,
    reorderQty: 24,
    category: "ingredient",
  },
  {
    id: "sku-004",
    name: "16oz glass bottles",
    unit: "cases",
    onHand: 18,
    dailyVelocity: 2.4,
    leadTimeDays: 21,
    supplier: "Berlin Packaging",
    unitCost: 28.0,
    reorderQty: 40,
    category: "packaging",
  },
  {
    id: "sku-005",
    name: "Black tea loose leaf",
    unit: "lbs",
    onHand: 85,
    dailyVelocity: 6.0,
    leadTimeDays: 10,
    supplier: "Wholesome Sweeteners",
    unitCost: 2.1,
    reorderQty: 120,
    category: "ingredient",
  },
  {
    id: "sku-006",
    name: "Shrink sleeve labels",
    unit: "rolls",
    onHand: 11,
    dailyVelocity: 0.8,
    leadTimeDays: 14,
    supplier: "Berlin Packaging",
    unitCost: 45.0,
    reorderQty: 20,
    category: "packaging",
  },
  {
    id: "sku-007",
    name: "Swing-top caps",
    unit: "bags",
    onHand: 40,
    dailyVelocity: 2.2,
    leadTimeDays: 7,
    supplier: "Berlin Packaging",
    unitCost: 18.0,
    reorderQty: 60,
    category: "packaging",
  },
  {
    id: "sku-008",
    name: "Citric acid",
    unit: "lbs",
    onHand: 62,
    dailyVelocity: 3.1,
    leadTimeDays: 5,
    supplier: "Spectrum Chemical",
    unitCost: 4.5,
    reorderQty: 80,
    category: "ingredient",
  },
  {
    id: "sku-009",
    name: "Green tea loose leaf",
    unit: "lbs",
    onHand: 54,
    dailyVelocity: 4.5,
    leadTimeDays: 10,
    supplier: "Wholesome Sweeteners",
    unitCost: 2.8,
    reorderQty: 100,
    category: "ingredient",
  },
  {
    id: "sku-010",
    name: "Kombucha flavor packets",
    unit: "boxes",
    onHand: 30,
    dailyVelocity: 1.8,
    leadTimeDays: 12,
    supplier: "Spectrum Chemical",
    unitCost: 22.0,
    reorderQty: 50,
    category: "other",
  },
];

export const BRAND_NAME = "Han's Kombucha";
